name: markdown

on:
  pull_request:
    # TODO: GitHub Actions' globbing is v. confusing.
    paths:
      - '*.md'
      - '**/*.md'
  push:
    branches:
      - master
    paths:
      - '*.md'
      - '**/*.md'
  schedule:
    - cron: 0 19 * * 2

jobs:
  markdown:
    name: markdown
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: markdown-spellcheck
        uses: ./.github/actions/markdown-spellcheck
      - name: write-good
        uses: ./.github/actions/write-good
