name: markdown

on:
  pull_request:
    # TODO: GitHub Actions' globbing is v. confusing. How do we limit this to **/*.md?
  push:
    branches:
      - master
  schedule:
    - cron: 0 19 * * 2

jobs:
  markdown:
    name: markdown
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: markdown-spellcheck
        uses: ./.github/actions/markdown-spellcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: write-good
        uses: ./.github/actions/write-good
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
