name: markdown

on:
  pull_request:
    # TODO: GitHub Actions' globbing is v. confusing. How do we limit this to **/*.md?
  push:
    branches:
      - master
  schedule:
    - cron: 0 19 * * 2

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: roboticcheese/github-action-cspell@v1
      - uses: roboticcheese/github-action-write-good@v1
