name: terraform

on:
  pull_request:
    # TODO: GitHub Actions' globbing is v. confusing. How do we limit this to terraform/**/*?
  push:
    branches:
      - master
  schedule:
    - cron: 0 19 * * 2

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: terraform-fmt
        uses: hashicorp/terraform-github-actions/fmt@master
        # Despite being in the GitHub actions docs, using "working-directory:"
        # throws an error about an invalid workflow file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: terraform/
      - name: terraform-init
        uses: hashicorp/terraform-github-actions/init@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: terraform/
          TF_ACTION_TFE_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
      - name: terraform-validate
        uses: hashicorp/terraform-github-actions/validate@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: terraform/
      # TODO: The digitalocean_kubernetes_cluster resource's state includes private key
      # data that can show up in the output of a plan or apply.
      # - name: terraform-plan
      #   uses: hashicorp/terraform-github-actions/plan@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     TF_ACTION_WORKING_DIR: terraform/
      #     TF_ACTION_TFE_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
      #     TF_VAR_digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      # - name: terraform-apply
      #   uses: hashicorp/terraform-github-actions/apply@master
      #   if: github.event_name == 'push' && github.ref == 'master'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     TF_ACTION_WORKING_DIR: terraform/
      #     TF_ACTION_TFE_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
      #     TF_VAR_digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
